@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "Trie#getAlphabeticalListWithPrefix(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": false,
    "cutClient": false,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "BothDirections" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 5,
    "showCallOrder": true,
    "edgeMode": "TypesAndMethods", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": true
  },
  "rootClass": "Trie",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_2615354 { 
   	label=Trie
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1244810606 { 
   	label=Trie
	labeljust=l
	fillcolor=white
	style=filled
   
   Trie2615354XXXgetAlphabeticalListWithPrefix1808118735[
	label="+ getAlphabeticalListWithPrefix(prefix: String): List<String>"
	style=filled
	fillcolor=white
	tooltip="Trie

&#10;  Retrieve from the trie an alphabetically sorted list of all words&#10;  beginning with a particular prefix.&#10; &#10;  @param prefix The prefix with which all words start.&#10;  @return The list of words beginning with the prefix, or an empty list if&#10;  the prefix was not found.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_591714562 { 
   	label=TrieDriver
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1932118382 { 
   	label=TrieDriver
	labeljust=l
	fillcolor=white
	style=filled
   
   TrieDriver591714562XXXmain1859653459[
	label="+ main(args: String[])"
	style=filled
	fillcolor=white
	tooltip="TrieDriver

null"
	fontcolor=darkgreen
];

TrieDriver591714562XXXtest3719352354[
	label="+ test3(in: Scanner)"
	style=filled
	fillcolor=white
	tooltip="TrieDriver

&#10; &#10;  Test out the Trie implementation for prefix search. Expect a list on standard in of&#10;  the words and the data to be inserted and then a second line that&#10;  searches for prefixes in the Trie.&#10; &#10;  For example&#10;  abacus 12 abasement 34 abase 56 abroad 67 aloud 3 all 34 allowed 43 allow 32 allowance 11 abroad 12&#10;  aba all br&#10; &#10;  aba: [abacus, abase, abasement]&#10;  all: [all, allow, allowance, allowed]&#10; &#10; "
	fontcolor=darkgreen
];
} 
} 

'edges    
TrieDriver591714562XXXmain1859653459 -> TrieDriver591714562XXXtest3719352354[label=4];
TrieDriver591714562XXXtest3719352354 -> Trie2615354XXXgetAlphabeticalListWithPrefix1808118735[label=11];
    
}
@enduml